training:
  learning_rate: 0.0001
  weight_decay: 0.01
  precision: 16-mixed
  strategy: auto
  training_steps: 280000
  ckpt_dir: ./ckpt/trained
  dataloader:
    batch_size: 22
    num_workers: 4
    pin_memory: True
    shuffle: True

logger:
  target: utils.CustomLogger
  params:
    log_frequency: 500
    n_examples: 2
    unconditional_guidance_scale: 7.5
    sample: True
    use_ddim: True
    ddim_steps: 50
    ddim_intermediates: 5
    ddim_eta: 0.0
    plot_denoise_rows: False
    plot_diffusion_rows: False

dataset:
  target: dataset.CompArt
  params:
    dataset_path: thejinzhe/CompArt
    split: train
    dtype: float32
    image_size: 512
    drop_caption_prob: 0.5
    drop_art_style_prob: 0.0
    keep_all_PoA_prob: 0.1
    drop_all_PoA_prob: 0.1
    drop_each_PoA_prob: 0.5

model:
  target: models.ArtDaptedModel
  init_path: ./ckpt/init/ArtDapterTSC.ckpt
  sd_locked: True
  params:
    art_style_strength: 1
    PoA_strength: 1
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "image"
    cond_stage_key: "caption"
    image_size: 64
    channels: 4
    cond_stage_trainable: false
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    
    artdapter_config:
      target: models.ArtDapterTSC
      params:
        connector_in_dim: 2048

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 4
        model_channels: 320
        out_channels: 4
        num_res_blocks: 2
        attention_resolutions: [4, 2, 1]
        channel_mult: [1, 2, 4, 4]
        use_checkpoint: False
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.T5Embedder
      params:
        max_length: 512
